import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Sidebar from "@/components/sidebar/sidebar";
import Appbar from "@/components/appbar/appbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"flex flex-row h-screen overflow-hidden "}>
      <Sidebar />
      <div className={"flex flex-col flex-1"}>
        <Appbar />
          <div className={"p-4 flex-1 flex w-full h-full"}>
              {children}
      </div>
      </div>

      </body>
    </html>
  );
}
